services:
  - type: web
    name: flaskapp
    env: python
    region: oregon
    plan: standard
    branch: breaking-change
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
